spring:
  datasource:
    # DB設定
    url: jdbc:postgresql://localhost:5433/airline_reservation
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}  # Docker コンテナ作成時に設定したパスワードを入力
    driver-class-name: org.postgresql.Driver

mybatis:
  # XML マッパーファイルの位置指定（resources/mapper/ 配下の全 XML）
  mapper-locations: classpath:mapper/**/*.xml
  # パッケージ名を省略できるようデフォルトパッケージを指定
  type-aliases-package: airlineReservation.infra.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: v9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B?E(G+KbPeShVmYq
  expiration: 1800000