-- DB초기화
DROP TABLE IF EXISTS passenger_details CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS schedule_seats CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS schedule_templates CASCADE;
DROP TABLE IF EXISTS airports CASCADE;
DROP TABLE IF EXISTS aircrafts CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;

-- 유저 종류
CREATE TABLE user_roles (
    role_code INT PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE user_roles IS '유저 종류';
COMMENT ON COLUMN user_roles.role_code IS '권한 코드';
COMMENT ON COLUMN user_roles.role_name IS '권한 이름';
COMMENT ON COLUMN user_roles.created_by IS '최초 등록 유저 ID';
COMMENT ON COLUMN user_roles.created_at IS '최초 등록 일시';
COMMENT ON COLUMN user_roles.updated_by IS '최종 수정 유저 ID';
COMMENT ON COLUMN user_roles.updated_at IS '최종 수정 일시';

-- 유저 테이블
CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code INT NOT NULL,
    user_name VARCHAR(50) NOT NULL,
    birth_date DATE NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone_number VARCHAR(20) NOT NULL,
    password VARCHAR(255) NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_code) REFERENCES user_roles(role_code)
);

COMMENT ON TABLE users IS '유저';
COMMENT ON COLUMN users.user_id IS '유저 ID';
COMMENT ON COLUMN users.role_code IS '권한 코드';
COMMENT ON COLUMN users.user_name IS '회원 이름';
COMMENT ON COLUMN users.birth_date IS '생년월일';
COMMENT ON COLUMN users.email IS '이메일 주소';
COMMENT ON COLUMN users.phone_number IS '휴대폰 번호';
COMMENT ON COLUMN users.password IS '비밀번호';
COMMENT ON COLUMN users.is_deleted IS '탈퇴 여부';
COMMENT ON COLUMN users.created_by IS '최초 등록 유저 ID';
COMMENT ON COLUMN users.created_at IS '최초 등록 일시';
COMMENT ON COLUMN users.updated_by IS '최종 수정 유저 ID';
COMMENT ON COLUMN users.updated_at IS '최종 수정 일시';


-- 항공기 마스터
CREATE TABLE aircrafts (
    aircraft_id VARCHAR(10) PRIMARY KEY,
    aircraft_name VARCHAR(50) NOT NULL,
    row_count INT NOT NULL,
    column_count INT NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE aircrafts IS '항공기';
COMMENT ON COLUMN aircrafts.aircraft_id IS '항공기 ID';
COMMENT ON COLUMN aircrafts.aircraft_name IS '항공기 기종명';
COMMENT ON COLUMN aircrafts.row_count IS '총 행수';
COMMENT ON COLUMN aircrafts.column_count IS '총 열수';
COMMENT ON COLUMN aircrafts.is_deleted IS '삭제 여부';
COMMENT ON COLUMN aircrafts.created_by IS '최초 등록 유저 ID';
COMMENT ON COLUMN aircrafts.created_at IS '최초 등록 일시';
COMMENT ON COLUMN aircrafts.updated_by IS '최종 수정 유저 ID';
COMMENT ON COLUMN aircrafts.updated_at IS '최종 수정 일시';


-- 공항 마스터
CREATE TABLE airports (
    airport_id VARCHAR(10) PRIMARY KEY,
    airport_name_ko VARCHAR(100) NOT NULL,
    airport_name_en VARCHAR(100) NOT NULL,
    country VARCHAR(50) NOT NULL,
    city VARCHAR(50) NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE airports IS '공항';
COMMENT ON COLUMN airports.airport_id IS '공항 코드';
COMMENT ON COLUMN airports.airport_name_ko IS '공항 한글명';
COMMENT ON COLUMN airports.airport_name_en IS '공항 영문명';
COMMENT ON COLUMN airports.country IS '국가명';
COMMENT ON COLUMN airports.city IS '도시명';
COMMENT ON COLUMN airports.is_deleted IS '운영 중단 여부';
COMMENT ON COLUMN airports.created_by IS '최초 등록 유저 ID';
COMMENT ON COLUMN airports.created_at IS '최초 등록 일시';
COMMENT ON COLUMN airports.updated_by IS '최종 수정 유저 ID';
COMMENT ON COLUMN airports.updated_at IS '최종 수정 일시';

-- 운항 템플릿
CREATE TABLE schedule_templates (
    template_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aircraft_id          VARCHAR(10) NOT NULL,
    departure_airport_id VARCHAR(10) NOT NULL,
    arrival_airport_id   VARCHAR(10) NOT NULL,
    start_date           DATE NOT NULL,
    end_date             DATE NOT NULL,
    departure_time       TIME NOT NULL,
    arrival_time         TIME NOT NULL,
    price                INTEGER NOT NULL,
    is_monday            BOOLEAN DEFAULT FALSE NOT NULL,
    is_tuesday           BOOLEAN DEFAULT FALSE NOT NULL,
    is_wednesday         BOOLEAN DEFAULT FALSE NOT NULL,
    is_thursday          BOOLEAN DEFAULT FALSE NOT NULL,
    is_friday            BOOLEAN DEFAULT FALSE NOT NULL,
    is_saturday          BOOLEAN DEFAULT FALSE NOT NULL,
    is_sunday            BOOLEAN DEFAULT FALSE NOT NULL,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (aircraft_id) REFERENCES aircrafts(aircraft_id),
    FOREIGN KEY (departure_airport_id) REFERENCES airports(airport_id),
    FOREIGN KEY (arrival_airport_id) REFERENCES airports(airport_id)
);

COMMENT ON TABLE schedule_templates IS '정기 운항 템플릿 마스터';
COMMENT ON COLUMN schedule_templates.template_id IS '템플릿 ID (PK)';
COMMENT ON COLUMN schedule_templates.aircraft_id IS '비행기 ID (FK)';
COMMENT ON COLUMN schedule_templates.departure_airport_id IS '출발 공항 ID (FK)';
COMMENT ON COLUMN schedule_templates.arrival_airport_id IS '도착 공항 ID (FK)';
COMMENT ON COLUMN schedule_templates.start_date IS '정기 운항 시작일';
COMMENT ON COLUMN schedule_templates.end_date IS '정기 운항 종료일';
COMMENT ON COLUMN schedule_templates.departure_time IS '출발 시각';
COMMENT ON COLUMN schedule_templates.arrival_time IS '도착 시각';
COMMENT ON COLUMN schedule_templates.price IS '요금';
COMMENT ON COLUMN schedule_templates.is_monday IS '월요일 운항 여부';
COMMENT ON COLUMN schedule_templates.is_tuesday IS '화요일 운항 여부';
COMMENT ON COLUMN schedule_templates.is_wednesday IS '수요일 운항 여부';
COMMENT ON COLUMN schedule_templates.is_thursday IS '목요일 운항 여부';
COMMENT ON COLUMN schedule_templates.is_friday IS '금요일 운항 여부';
COMMENT ON COLUMN schedule_templates.is_saturday IS '토요일 운항 여부';
COMMENT ON COLUMN schedule_templates.is_sunday IS '일요일 운항 여부';

-- 운항 스케줄
CREATE TABLE schedules (
    schedule_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id          INT,
    aircraft_id          VARCHAR(10) NOT NULL,
    departure_airport_id VARCHAR(10) NOT NULL,
    arrival_airport_id   VARCHAR(10) NOT NULL,
    departure_datetime   TIMESTAMP NOT NULL,
    arrival_datetime     TIMESTAMP NOT NULL,
    status               VARCHAR(20) DEFAULT 'SCHEDULED' NOT NULL,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (template_id) REFERENCES schedule_templates(template_id) ON DELETE SET NULL,
    FOREIGN KEY (aircraft_id) REFERENCES aircrafts(aircraft_id),
    FOREIGN KEY (departure_airport_id) REFERENCES airports(airport_id),
    FOREIGN KEY (arrival_airport_id) REFERENCES airports(airport_id)
);

COMMENT ON TABLE schedules IS '실제 일자별 운항 스케줄';
COMMENT ON COLUMN schedules.schedule_id IS '스케줄 ID (PK)';
COMMENT ON COLUMN schedules.template_id IS '연결된 템플릿 ID (FK)';
COMMENT ON COLUMN schedules.aircraft_id IS '비행기 ID (FK)';
COMMENT ON COLUMN schedules.departure_airport_id IS '출발 공항 ID (FK)';
COMMENT ON COLUMN schedules.arrival_airport_id IS '도착 공항 ID (FK)';
COMMENT ON COLUMN schedules.departure_datetime IS '실제 출발 일시 (날짜+시간)';
COMMENT ON COLUMN schedules.arrival_datetime IS '실제 도착 일시 (날짜+시간)';
COMMENT ON COLUMN schedules.status IS '운항 상태 (SCHEDULED, DELAYED, CANCELLED)';

-- 일정별 좌석상태
CREATE TABLE schedule_seats (
    scheduled_seat_no INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id INT NOT NULL,
    seat_name VARCHAR(10) NOT NULL,
    status VARCHAR(20) DEFAULT 'AVAILABLE',
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (schedule_id) REFERENCES schedules(schedule_id),
    CONSTRAINT uq_schedule_seat UNIQUE (schedule_id, seat_name)
);

COMMENT ON TABLE schedule_seats IS '일정별 좌석상태';
COMMENT ON COLUMN schedule_seats.scheduled_seat_no IS '일정별 좌석 상태 no';
COMMENT ON COLUMN schedule_seats.schedule_id IS '운항 일정 고유 ID';
COMMENT ON COLUMN schedule_seats.seat_name IS '좌석 번호';
COMMENT ON COLUMN schedule_seats.status IS '좌석 예약 상태';
COMMENT ON COLUMN schedule_seats.created_by IS '최초 등록 유저 ID';
COMMENT ON COLUMN schedule_seats.created_at IS '최초 등록 일시';
COMMENT ON COLUMN schedule_seats.updated_by IS '최종 수정 유저 ID';
COMMENT ON COLUMN schedule_seats.updated_at IS '최종 수정 일시';


-- 예약
CREATE TABLE bookings (
    booking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    schedule_id INT NOT NULL,
    total_price INT NOT NULL,
    booking_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) DEFAULT 'COMPLETED',
    is_deleted BOOLEAN DEFAULT FALSE,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (schedule_id) REFERENCES schedules(schedule_id)
);

COMMENT ON TABLE bookings IS '예약';
COMMENT ON COLUMN bookings.booking_id IS '예약 일련번호';
COMMENT ON COLUMN bookings.user_id IS '예약 회 ID';
COMMENT ON COLUMN bookings.schedule_id IS '운항 일정 ID';
COMMENT ON COLUMN bookings.total_price IS '총 결제 금액';
COMMENT ON COLUMN bookings.booking_time IS '예약 일시';
COMMENT ON COLUMN bookings.status IS '예약 진행 상태';
COMMENT ON COLUMN bookings.is_deleted IS '예약 내역 삭제 여부';
COMMENT ON COLUMN bookings.created_by IS '최초 등록 유저 ID';
COMMENT ON COLUMN bookings.created_at IS '최초 등록 일시';
COMMENT ON COLUMN bookings.updated_by IS '최종 수정 유저 ID';
COMMENT ON COLUMN bookings.updated_at IS '최종 수정 일시';


-- 탑승객 예약상세
CREATE TABLE passenger_details (
    passenger_detail_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT NOT NULL,
    passenger_name VARCHAR(50) NOT NULL,
    schedule_seat_no INT NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (booking_id) REFERENCES bookings(booking_id),
    FOREIGN KEY (schedule_seat_no) REFERENCES schedule_seats(scheduled_seat_no)
);

COMMENT ON TABLE passenger_details IS '탑승객 예약상세';
COMMENT ON COLUMN passenger_details.passenger_detail_id IS '탑승객 상세 일련번호';
COMMENT ON COLUMN passenger_details.booking_id IS '예약 일련번호';
COMMENT ON COLUMN passenger_details.passenger_name IS '탑승객 실명';
COMMENT ON COLUMN passenger_details.schedule_seat_no IS '일정별 좌석 상태 no';
COMMENT ON COLUMN passenger_details.is_deleted IS '삭제 여부';
COMMENT ON COLUMN passenger_details.created_by IS '최초 등록 유저 ID';
COMMENT ON COLUMN passenger_details.created_at IS '최초 등록 일시';
COMMENT ON COLUMN passenger_details.updated_by IS '최종 수정 유저 ID';
COMMENT ON COLUMN passenger_details.updated_at IS '최종 수정 일시';

-- 논리 삭제 이외의 좌석 데이터에 대해서만 유니크 인덱스 생성
CREATE UNIQUE INDEX uq_active_passenger_seat
ON passenger_details (schedule_seat_no)
WHERE is_deleted = FALSE;

-- 초기 데이터 세팅
INSERT INTO user_roles (role_code, role_name) VALUES (1, '일반유저'), (2, '관리자');

-- 유저 데이터 등록
INSERT INTO users (role_code, user_name, birth_date, email, phone_number, password, created_by, updated_by)
    VALUES (2, '관리자', '1990-01-15', 'admin@admin.com', '010-1234-5678',
    '$2a$10$zsGQp/wcGuJLtLmjb2oFL.TCFcZVE4QZcbqWLLBlHX1SpFokM60c2', 1, 1
);

-- 공항 초기 데이터 세팅
INSERT INTO airports (airport_id, airport_name_ko, airport_name_en, country, city, is_deleted)
VALUES
    ('ICN', '인천국제공항', 'Incheon International Airport', '대한민국', '서울', FALSE),
    ('GMP', '김포국제공항', 'Gimpo International Airport', '대한민국', '서울', FALSE),
    ('CJU', '제주국제공항', 'Jeju International Airport', '대한민국', '제주', FALSE),
    ('PUS', '김해국제공항', 'Gimhae International Airport', '대한민국', '부산', FALSE),
    ('NRT', '나리타국제공항', 'Narita International Airport', '일본', '도쿄', FALSE),
    ('HND', '하네다국제공항', 'Tokyo Haneda International Airport', '일본', '도쿄', FALSE),
    ('KIX', '간사이국제공항', 'Kansai International Airport', '일본', '오사카', FALSE),
    ('FUK', '후쿠오카공항', 'Fukuoka Airport', '일본', '후쿠오카', FALSE),
    ('CTS', '신치토세공항', 'New Chitose Airport', '일본', '삿포로', FALSE)
ON CONFLICT (airport_id) DO NOTHING;

-- 항공기 초기 데이터 세팅
INSERT INTO aircrafts (aircraft_id, aircraft_name, row_count, column_count, is_deleted)
VALUES
    ('B737-800', 'Boeing 737-800', 15, 6, FALSE),
    ('A320-200', 'Airbus A320-200', 12, 5, FALSE),
    ('A321-NEO', 'Airbus A321neo', 13, 6, FALSE),
    ('B787-9',   'Boeing 787-9', 10, 9, FALSE),
    ('A350-900', 'Airbus A350-900', 12, 6, FALSE),
    ('B777-300ER', 'Boeing 777-300ER', 10, 9, FALSE)
ON CONFLICT (aircraft_id) DO NOTHING;