-- DB初期化
DROP TABLE IF EXISTS passenger_details CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS schedule_seats CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS schedule_templates CASCADE;
DROP TABLE IF EXISTS airports CASCADE;
DROP TABLE IF EXISTS aircrafts CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;

-- ユーザー種別
CREATE TABLE user_roles (
    role_code INT PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE user_roles IS 'ユーザー種別';
COMMENT ON COLUMN user_roles.role_code IS '権限コード';
COMMENT ON COLUMN user_roles.role_name IS '権限名';
COMMENT ON COLUMN user_roles.created_by IS '初回登録ユーザーID';
COMMENT ON COLUMN user_roles.created_at IS '初回登録日時';
COMMENT ON COLUMN user_roles.updated_by IS '最終更新ユーザーID';
COMMENT ON COLUMN user_roles.updated_at IS '最終更新日時';

-- ユーザーテーブル
CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code INT NOT NULL,
    user_name VARCHAR(50) NOT NULL,
    birth_date DATE NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone_number VARCHAR(20) NOT NULL,
    password VARCHAR(255) NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_code) REFERENCES user_roles(role_code)
);

COMMENT ON TABLE users IS 'ユーザー';
COMMENT ON COLUMN users.user_id IS 'ユーザーID';
COMMENT ON COLUMN users.role_code IS '権限コード';
COMMENT ON COLUMN users.user_name IS '会員名';
COMMENT ON COLUMN users.birth_date IS '生年月日';
COMMENT ON COLUMN users.email IS 'メールアドレス';
COMMENT ON COLUMN users.phone_number IS '携帯電話番号';
COMMENT ON COLUMN users.password IS 'パスワード';
COMMENT ON COLUMN users.is_deleted IS '退会フラグ';
COMMENT ON COLUMN users.created_by IS '初回登録ユーザーID';
COMMENT ON COLUMN users.created_at IS '初回登録日時';
COMMENT ON COLUMN users.updated_by IS '最終更新ユーザーID';
COMMENT ON COLUMN users.updated_at IS '最終更新日時';


-- 航空機マスタ
CREATE TABLE aircrafts (
    aircraft_id VARCHAR(10) PRIMARY KEY,
    aircraft_name VARCHAR(50) NOT NULL,
    row_count INT NOT NULL,
    column_count INT NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE aircrafts IS '航空機';
COMMENT ON COLUMN aircrafts.aircraft_id IS '航空機ID';
COMMENT ON COLUMN aircrafts.aircraft_name IS '航空機機種名';
COMMENT ON COLUMN aircrafts.row_count IS '総行数';
COMMENT ON COLUMN aircrafts.column_count IS '総列数';
COMMENT ON COLUMN aircrafts.is_deleted IS '削除フラグ';
COMMENT ON COLUMN aircrafts.created_by IS '初回登録ユーザーID';
COMMENT ON COLUMN aircrafts.created_at IS '初回登録日時';
COMMENT ON COLUMN aircrafts.updated_by IS '最終更新ユーザーID';
COMMENT ON COLUMN aircrafts.updated_at IS '最終更新日時';


-- 空港マスタ
CREATE TABLE airports (
    airport_id VARCHAR(10) PRIMARY KEY,
    airport_name_ko VARCHAR(100) NOT NULL,
    airport_name_en VARCHAR(100) NOT NULL,
    country VARCHAR(50) NOT NULL,
    city VARCHAR(50) NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE airports IS '空港';
COMMENT ON COLUMN airports.airport_id IS '空港コード';
COMMENT ON COLUMN airports.airport_name_ko IS '空港名（日本語）';
COMMENT ON COLUMN airports.airport_name_en IS '空港名（英語）';
COMMENT ON COLUMN airports.country IS '国名';
COMMENT ON COLUMN airports.city IS '都市名';
COMMENT ON COLUMN airports.is_deleted IS '運航停止フラグ';
COMMENT ON COLUMN airports.created_by IS '初回登録ユーザーID';
COMMENT ON COLUMN airports.created_at IS '初回登録日時';
COMMENT ON COLUMN airports.updated_by IS '最終更新ユーザーID';
COMMENT ON COLUMN airports.updated_at IS '最終更新日時';

-- 運航テンプレート
CREATE TABLE schedule_templates (
    template_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aircraft_id          VARCHAR(10) NOT NULL,
    departure_airport_id VARCHAR(10) NOT NULL,
    arrival_airport_id   VARCHAR(10) NOT NULL,
    start_date           DATE NOT NULL,
    end_date             DATE NOT NULL,
    departure_time       TIME NOT NULL,
    arrival_time         TIME NOT NULL,
    price                INTEGER NOT NULL,
    is_monday            BOOLEAN DEFAULT FALSE NOT NULL,
    is_tuesday           BOOLEAN DEFAULT FALSE NOT NULL,
    is_wednesday         BOOLEAN DEFAULT FALSE NOT NULL,
    is_thursday          BOOLEAN DEFAULT FALSE NOT NULL,
    is_friday            BOOLEAN DEFAULT FALSE NOT NULL,
    is_saturday          BOOLEAN DEFAULT FALSE NOT NULL,
    is_sunday            BOOLEAN DEFAULT FALSE NOT NULL,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (aircraft_id) REFERENCES aircrafts(aircraft_id),
    FOREIGN KEY (departure_airport_id) REFERENCES airports(airport_id),
    FOREIGN KEY (arrival_airport_id) REFERENCES airports(airport_id)
);

COMMENT ON TABLE schedule_templates IS '定期運航テンプレートマスタ';
COMMENT ON COLUMN schedule_templates.template_id IS 'テンプレートID (PK)';
COMMENT ON COLUMN schedule_templates.aircraft_id IS '航空機ID (FK)';
COMMENT ON COLUMN schedule_templates.departure_airport_id IS '出発空港ID (FK)';
COMMENT ON COLUMN schedule_templates.arrival_airport_id IS '到着空港ID (FK)';
COMMENT ON COLUMN schedule_templates.start_date IS '定期運航開始日';
COMMENT ON COLUMN schedule_templates.end_date IS '定期運航終了日';
COMMENT ON COLUMN schedule_templates.departure_time IS '出発時刻';
COMMENT ON COLUMN schedule_templates.arrival_time IS '到着時刻';
COMMENT ON COLUMN schedule_templates.price IS '料金';
COMMENT ON COLUMN schedule_templates.is_monday IS '月曜日運航フラグ';
COMMENT ON COLUMN schedule_templates.is_tuesday IS '火曜日運航フラグ';
COMMENT ON COLUMN schedule_templates.is_wednesday IS '水曜日運航フラグ';
COMMENT ON COLUMN schedule_templates.is_thursday IS '木曜日運航フラグ';
COMMENT ON COLUMN schedule_templates.is_friday IS '金曜日運航フラグ';
COMMENT ON COLUMN schedule_templates.is_saturday IS '土曜日運航フラグ';
COMMENT ON COLUMN schedule_templates.is_sunday IS '日曜日運航フラグ';

-- 運航スケジュール
CREATE TABLE schedules (
    schedule_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id          INT,
    aircraft_id          VARCHAR(10) NOT NULL,
    departure_airport_id VARCHAR(10) NOT NULL,
    arrival_airport_id   VARCHAR(10) NOT NULL,
    departure_datetime   TIMESTAMP NOT NULL,
    arrival_datetime     TIMESTAMP NOT NULL,
    status               VARCHAR(20) DEFAULT 'SCHEDULED' NOT NULL,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (template_id) REFERENCES schedule_templates(template_id) ON DELETE SET NULL,
    FOREIGN KEY (aircraft_id) REFERENCES aircrafts(aircraft_id),
    FOREIGN KEY (departure_airport_id) REFERENCES airports(airport_id),
    FOREIGN KEY (arrival_airport_id) REFERENCES airports(airport_id)
);

COMMENT ON TABLE schedules IS '実日付別運航スケジュール';
COMMENT ON COLUMN schedules.schedule_id IS 'スケジュールID (PK)';
COMMENT ON COLUMN schedules.template_id IS '紐づくテンプレートID (FK)';
COMMENT ON COLUMN schedules.aircraft_id IS '航空機ID (FK)';
COMMENT ON COLUMN schedules.departure_airport_id IS '出発空港ID (FK)';
COMMENT ON COLUMN schedules.arrival_airport_id IS '到着空港ID (FK)';
COMMENT ON COLUMN schedules.departure_datetime IS '実際の出発日時（日付+時刻）';
COMMENT ON COLUMN schedules.arrival_datetime IS '実際の到着日時（日付+時刻）';
COMMENT ON COLUMN schedules.status IS '運航ステータス (SCHEDULED, DELAYED, CANCELLED)';

-- 便別座席状態
CREATE TABLE schedule_seats (
    scheduled_seat_no INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id INT NOT NULL,
    seat_name VARCHAR(10) NOT NULL,
    status VARCHAR(20) DEFAULT 'AVAILABLE',
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (schedule_id) REFERENCES schedules(schedule_id),
    CONSTRAINT uq_schedule_seat UNIQUE (schedule_id, seat_name)
);

COMMENT ON TABLE schedule_seats IS '便別座席状態';
COMMENT ON COLUMN schedule_seats.scheduled_seat_no IS '便別座席状態NO';
COMMENT ON COLUMN schedule_seats.schedule_id IS '運航スケジュール固有ID';
COMMENT ON COLUMN schedule_seats.seat_name IS '座席番号';
COMMENT ON COLUMN schedule_seats.status IS '座席予約ステータス';
COMMENT ON COLUMN schedule_seats.created_by IS '初回登録ユーザーID';
COMMENT ON COLUMN schedule_seats.created_at IS '初回登録日時';
COMMENT ON COLUMN schedule_seats.updated_by IS '最終更新ユーザーID';
COMMENT ON COLUMN schedule_seats.updated_at IS '最終更新日時';


-- 予約
CREATE TABLE bookings (
    booking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    schedule_id INT NOT NULL,
    total_price INT NOT NULL,
    booking_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) DEFAULT 'COMPLETED',
    is_deleted BOOLEAN DEFAULT FALSE,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (schedule_id) REFERENCES schedules(schedule_id)
);

COMMENT ON TABLE bookings IS '予約';
COMMENT ON COLUMN bookings.booking_id IS '予約連番';
COMMENT ON COLUMN bookings.user_id IS '予約ユーザーID';
COMMENT ON COLUMN bookings.schedule_id IS '運航スケジュールID';
COMMENT ON COLUMN bookings.total_price IS '合計支払金額';
COMMENT ON COLUMN bookings.booking_time IS '予約日時';
COMMENT ON COLUMN bookings.status IS '予約進行ステータス';
COMMENT ON COLUMN bookings.is_deleted IS '予約履歴削除フラグ';
COMMENT ON COLUMN bookings.created_by IS '初回登録ユーザーID';
COMMENT ON COLUMN bookings.created_at IS '初回登録日時';
COMMENT ON COLUMN bookings.updated_by IS '最終更新ユーザーID';
COMMENT ON COLUMN bookings.updated_at IS '最終更新日時';


-- 搭乗者予約詳細
CREATE TABLE passenger_details (
    passenger_detail_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT NOT NULL,
    passenger_name VARCHAR(50) NOT NULL,
    schedule_seat_no INT NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (booking_id) REFERENCES bookings(booking_id),
    FOREIGN KEY (schedule_seat_no) REFERENCES schedule_seats(scheduled_seat_no)
);

COMMENT ON TABLE passenger_details IS '搭乗者予約詳細';
COMMENT ON COLUMN passenger_details.passenger_detail_id IS '搭乗者詳細連番';
COMMENT ON COLUMN passenger_details.booking_id IS '予約連番';
COMMENT ON COLUMN passenger_details.passenger_name IS '搭乗者氏名';
COMMENT ON COLUMN passenger_details.schedule_seat_no IS '便別座席状態NO';
COMMENT ON COLUMN passenger_details.is_deleted IS '削除フラグ';
COMMENT ON COLUMN passenger_details.created_by IS '初回登録ユーザーID';
COMMENT ON COLUMN passenger_details.created_at IS '初回登録日時';
COMMENT ON COLUMN passenger_details.updated_by IS '最終更新ユーザーID';
COMMENT ON COLUMN passenger_details.updated_at IS '最終更新日時';

-- 論理削除以外の座席データに対してのみユニークインデックスを作成
CREATE UNIQUE INDEX uq_active_passenger_seat
ON passenger_details (schedule_seat_no)
WHERE is_deleted = FALSE;

-- 初期データ設定
INSERT INTO user_roles (role_code, role_name) VALUES (1, '一般ユーザー'), (2, '管理者');

-- ユーザーデータ登録
INSERT INTO users (role_code, user_name, birth_date, email, phone_number, password, created_by, updated_by)
    VALUES (2, '管理者', '1990-01-15', 'admin@admin.com', '010-1234-5678',
    '$2a$10$zsGQp/wcGuJLtLmjb2oFL.TCFcZVE4QZcbqWLLBlHX1SpFokM60c2', 1, 1
);

-- 空港初期データ設定
INSERT INTO airports (airport_id, airport_name_ko, airport_name_en, country, city, is_deleted)
VALUES
    ('ICN', '仁川国際空港', 'Incheon International Airport', '韓国', 'ソウル', FALSE),
    ('GMP', '金浦国際空港', 'Gimpo International Airport', '韓国', 'ソウル', FALSE),
    ('CJU', '済州国際空港', 'Jeju International Airport', '韓国', '済州', FALSE),
    ('PUS', '金海国際空港', 'Gimhae International Airport', '韓国', '釜山', FALSE),
    ('NRT', '成田国際空港', 'Narita International Airport', '日本', '東京', FALSE),
    ('HND', '羽田国際空港', 'Tokyo Haneda International Airport', '日本', '東京', FALSE),
    ('KIX', '関西国際空港', 'Kansai International Airport', '日本', '大阪', FALSE),
    ('FUK', '福岡空港', 'Fukuoka Airport', '日本', '福岡', FALSE),
    ('CTS', '新千歳空港', 'New Chitose Airport', '日本', '札幌', FALSE)
ON CONFLICT (airport_id) DO NOTHING;

-- 航空機初期データ設定
INSERT INTO aircrafts (aircraft_id, aircraft_name, row_count, column_count, is_deleted)
VALUES
    ('B737-800', 'Boeing 737-800', 15, 6, FALSE),
    ('A320-200', 'Airbus A320-200', 12, 5, FALSE),
    ('A321-NEO', 'Airbus A321neo', 13, 6, FALSE),
    ('B787-9',   'Boeing 787-9', 10, 9, FALSE),
    ('A350-900', 'Airbus A350-900', 12, 6, FALSE),
    ('B777-300ER', 'Boeing 777-300ER', 10, 9, FALSE)
ON CONFLICT (aircraft_id) DO NOTHING;
