package airlineReservation.domain.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   공항
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table airports
 */
public class Airport {
    /**
     * Database Column Remarks:
     *   공항 코드
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.airport_id
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    private String airportId;

    /**
     * Database Column Remarks:
     *   공항 한글명
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.airport_name_ko
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    private String airportNameKo;

    /**
     * Database Column Remarks:
     *   공항 영문명
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.airport_name_en
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    private String airportNameEn;

    /**
     * Database Column Remarks:
     *   국가명
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.country
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    private String country;

    /**
     * Database Column Remarks:
     *   도시명
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.city
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    private String city;

    /**
     * Database Column Remarks:
     *   운영 중단 여부
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.is_deleted
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    private Boolean isDeleted;

    /**
     * Database Column Remarks:
     *   최초 등록 유저 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.created_by
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    private Long createdBy;

    /**
     * Database Column Remarks:
     *   최초 등록 일시
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.created_at
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   최종 수정 유저 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.updated_by
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    private Long updatedBy;

    /**
     * Database Column Remarks:
     *   최종 수정 일시
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.updated_at
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.airport_id
     *
     * @return the value of airports.airport_id
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public String getAirportId() {
        return airportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.airport_id
     *
     * @param airportId the value for airports.airport_id
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public void setAirportId(String airportId) {
        this.airportId = airportId == null ? null : airportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.airport_name_ko
     *
     * @return the value of airports.airport_name_ko
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public String getAirportNameKo() {
        return airportNameKo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.airport_name_ko
     *
     * @param airportNameKo the value for airports.airport_name_ko
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public void setAirportNameKo(String airportNameKo) {
        this.airportNameKo = airportNameKo == null ? null : airportNameKo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.airport_name_en
     *
     * @return the value of airports.airport_name_en
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public String getAirportNameEn() {
        return airportNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.airport_name_en
     *
     * @param airportNameEn the value for airports.airport_name_en
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public void setAirportNameEn(String airportNameEn) {
        this.airportNameEn = airportNameEn == null ? null : airportNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.country
     *
     * @return the value of airports.country
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.country
     *
     * @param country the value for airports.country
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.city
     *
     * @return the value of airports.city
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.city
     *
     * @param city the value for airports.city
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.is_deleted
     *
     * @return the value of airports.is_deleted
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.is_deleted
     *
     * @param isDeleted the value for airports.is_deleted
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.created_by
     *
     * @return the value of airports.created_by
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.created_by
     *
     * @param createdBy the value for airports.created_by
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.created_at
     *
     * @return the value of airports.created_at
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.created_at
     *
     * @param createdAt the value for airports.created_at
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.updated_by
     *
     * @return the value of airports.updated_by
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.updated_by
     *
     * @param updatedBy the value for airports.updated_by
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.updated_at
     *
     * @return the value of airports.updated_at
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.updated_at
     *
     * @param updatedAt the value for airports.updated_at
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}