package airlineReservation.domain.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   좌석
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table seats
 */
public class Seat {
    /**
     * Database Column Remarks:
     *   기본 좌석 고유 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seats.seat_id
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    private Long seatId;

    /**
     * Database Column Remarks:
     *   좌석 번호
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seats.seat_name
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    private String seatName;

    /**
     * Database Column Remarks:
     *   항공기 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seats.aircraft_id
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    private String aircraftId;

    /**
     * Database Column Remarks:
     *   최초 등록 유저 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seats.created_by
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    private Long createdBy;

    /**
     * Database Column Remarks:
     *   최초 등록 일시
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seats.created_at
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   최종 수정 유저 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seats.updated_by
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    private Long updatedBy;

    /**
     * Database Column Remarks:
     *   최종 수정 일시
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seats.updated_at
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seats.seat_id
     *
     * @return the value of seats.seat_id
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public Long getSeatId() {
        return seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seats.seat_id
     *
     * @param seatId the value for seats.seat_id
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public void setSeatId(Long seatId) {
        this.seatId = seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seats.seat_name
     *
     * @return the value of seats.seat_name
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public String getSeatName() {
        return seatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seats.seat_name
     *
     * @param seatName the value for seats.seat_name
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public void setSeatName(String seatName) {
        this.seatName = seatName == null ? null : seatName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seats.aircraft_id
     *
     * @return the value of seats.aircraft_id
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public String getAircraftId() {
        return aircraftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seats.aircraft_id
     *
     * @param aircraftId the value for seats.aircraft_id
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public void setAircraftId(String aircraftId) {
        this.aircraftId = aircraftId == null ? null : aircraftId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seats.created_by
     *
     * @return the value of seats.created_by
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seats.created_by
     *
     * @param createdBy the value for seats.created_by
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seats.created_at
     *
     * @return the value of seats.created_at
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seats.created_at
     *
     * @param createdAt the value for seats.created_at
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seats.updated_by
     *
     * @return the value of seats.updated_by
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seats.updated_by
     *
     * @param updatedBy the value for seats.updated_by
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seats.updated_at
     *
     * @return the value of seats.updated_at
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seats.updated_at
     *
     * @param updatedAt the value for seats.updated_at
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}