/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package airlineReservation.infra.api;

import airlineReservation.infra.dto.CreateAccountRequest;
import airlineReservation.infra.dto.CreateAccountResponse;
import airlineReservation.infra.dto.CreateAircraftRequest;
import airlineReservation.infra.dto.CreateAircraftResponse;
import airlineReservation.infra.dto.CreateBookingRequest;
import airlineReservation.infra.dto.CreateBookingResponse;
import airlineReservation.infra.dto.CreateScheduleTemplateRequest;
import airlineReservation.infra.dto.CreateScheduleTemplateResponse;
import airlineReservation.infra.dto.DeleteAccountResponse;
import airlineReservation.infra.dto.DeleteAircraftRequest;
import airlineReservation.infra.dto.DeleteAircraftResponse;
import airlineReservation.infra.dto.DeleteBookingRequest;
import airlineReservation.infra.dto.DeleteBookingResponse;
import airlineReservation.infra.dto.DeleteScheduleRequest;
import airlineReservation.infra.dto.DeleteScheduleResponse;
import airlineReservation.infra.dto.DeleteScheduleTemplateRequest;
import airlineReservation.infra.dto.DeleteScheduleTemplateResponse;
import airlineReservation.infra.dto.ErrorResponse;
import airlineReservation.infra.dto.GetAirportsRequest;
import airlineReservation.infra.dto.GetAirportsResponse;
import airlineReservation.infra.dto.GetFlightsRequest;
import airlineReservation.infra.dto.GetFlightsResponse;
import airlineReservation.infra.dto.GetSeatsRequest;
import airlineReservation.infra.dto.GetSeatsResponse;
import airlineReservation.infra.dto.LoginRequest;
import airlineReservation.infra.dto.LoginResponse;
import airlineReservation.infra.dto.SearchAircraftRequest;
import airlineReservation.infra.dto.SearchAircraftResponse;
import airlineReservation.infra.dto.SearchBookingByAdminRequest;
import airlineReservation.infra.dto.SearchBookingRequest;
import airlineReservation.infra.dto.SearchBookingResponse;
import airlineReservation.infra.dto.SearchScheduleRequest;
import airlineReservation.infra.dto.SearchScheduleResponse;
import airlineReservation.infra.dto.SearchScheduleTemplateRequest;
import airlineReservation.infra.dto.SearchScheduleTemplateResponse;
import airlineReservation.infra.dto.UpdateAircraftRequest;
import airlineReservation.infra.dto.UpdateAircraftResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-08-30T17:47:13.211020+09:00[Asia/Tokyo]", comments = "Generator version: 7.4.0")
@Validated
@Tag(name = "api", description = "the api API")
public interface ApiApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /api/v1/admin/searchBooking : 管理者予約検索API
     *
     * @param searchBookingByAdminRequest  (required)
     * @return 管理者予約検索成功 (status code 200)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "adminSearchBooking",
        summary = "管理者予約検索API",
        responses = {
            @ApiResponse(responseCode = "200", description = "管理者予約検索成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SearchBookingResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/admin/searchBooking",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<SearchBookingResponse> adminSearchBooking(
        @Parameter(name = "SearchBookingByAdminRequest", description = "", required = true) @Valid @RequestBody SearchBookingByAdminRequest searchBookingByAdminRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"bookingList\" : [ { \"totalPrice\" : 5, \"passengerCount\" : 5, \"arrivalDatetime\" : \"2000-01-23T04:56:07.000+00:00\", \"departureDatetime\" : \"2000-01-23T04:56:07.000+00:00\", \"userName\" : \"userName\", \"userId\" : 6, \"seats\" : [ { \"seat\" : \"seat\", \"name\" : \"name\" }, { \"seat\" : \"seat\", \"name\" : \"name\" } ], \"bookingId\" : 0, \"aircraftId\" : \"aircraftId\", \"arrivalAirportId\" : \"arrivalAirportId\", \"bookedTime\" : \"2000-01-23T04:56:07.000+00:00\", \"scheduleId\" : 1, \"departureAirportId\" : \"departureAirportId\", \"status\" : \"status\" }, { \"totalPrice\" : 5, \"passengerCount\" : 5, \"arrivalDatetime\" : \"2000-01-23T04:56:07.000+00:00\", \"departureDatetime\" : \"2000-01-23T04:56:07.000+00:00\", \"userName\" : \"userName\", \"userId\" : 6, \"seats\" : [ { \"seat\" : \"seat\", \"name\" : \"name\" }, { \"seat\" : \"seat\", \"name\" : \"name\" } ], \"bookingId\" : 0, \"aircraftId\" : \"aircraftId\", \"arrivalAirportId\" : \"arrivalAirportId\", \"bookedTime\" : \"2000-01-23T04:56:07.000+00:00\", \"scheduleId\" : 1, \"departureAirportId\" : \"departureAirportId\", \"status\" : \"status\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /api/v1/account/create : 会員登録API
     *
     * @param createAccountRequest  (required)
     * @return 会員登録成功 (status code 201)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "createAccount",
        summary = "会員登録API",
        responses = {
            @ApiResponse(responseCode = "201", description = "会員登録成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateAccountResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/account/create",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<CreateAccountResponse> createAccount(
        @Parameter(name = "CreateAccountRequest", description = "", required = true) @Valid @RequestBody CreateAccountRequest createAccountRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"success\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /api/v1/admin/createAircraft : 航空機登録API
     *
     * @param createAircraftRequest  (required)
     * @return 航空機登録成功 (status code 201)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "createAircraft",
        summary = "航空機登録API",
        responses = {
            @ApiResponse(responseCode = "201", description = "航空機登録成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateAircraftResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/admin/createAircraft",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<CreateAircraftResponse> createAircraft(
        @Parameter(name = "CreateAircraftRequest", description = "", required = true) @Valid @RequestBody CreateAircraftRequest createAircraftRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"success\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /api/v1/createBooking : 予約登録API
     *
     * @param createBookingRequest  (required)
     * @return 予約登録成功 (status code 201)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "createBooking",
        summary = "予約登録API",
        responses = {
            @ApiResponse(responseCode = "201", description = "予約登録成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateBookingResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/createBooking",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<CreateBookingResponse> createBooking(
        @Parameter(name = "CreateBookingRequest", description = "", required = true) @Valid @RequestBody CreateBookingRequest createBookingRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"bookingId\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /api/v1/admin/createScheduleTemplate : スケジュール登録API
     *
     * @param createScheduleTemplateRequest  (required)
     * @return スケジュール登録成功 (status code 201)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "createSchedule",
        summary = "スケジュール登録API",
        responses = {
            @ApiResponse(responseCode = "201", description = "スケジュール登録成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateScheduleTemplateResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/admin/createScheduleTemplate",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<CreateScheduleTemplateResponse> createSchedule(
        @Parameter(name = "CreateScheduleTemplateRequest", description = "", required = true) @Valid @RequestBody CreateScheduleTemplateRequest createScheduleTemplateRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"success\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /api/v1/account/delete : 会員退会API
     *
     * @return 会員退会成功 (status code 201)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "deleteAccount",
        summary = "会員退会API",
        responses = {
            @ApiResponse(responseCode = "201", description = "会員退会成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DeleteAccountResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/account/delete",
        produces = { "application/json" }
    )
    
    default ResponseEntity<DeleteAccountResponse> deleteAccount(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"success\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /api/v1/admin/deleteAircraft : 航空機削除API
     *
     * @param deleteAircraftRequest  (required)
     * @return 航空機削除成功 (status code 201)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "deleteAircraft",
        summary = "航空機削除API",
        responses = {
            @ApiResponse(responseCode = "201", description = "航空機削除成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DeleteAircraftResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/admin/deleteAircraft",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<DeleteAircraftResponse> deleteAircraft(
        @Parameter(name = "DeleteAircraftRequest", description = "", required = true) @Valid @RequestBody DeleteAircraftRequest deleteAircraftRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"success\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /api/v1/admin/deleteBooking : 予約キャンセルAPI
     *
     * @param deleteBookingRequest  (required)
     * @return 予約キャンセル成功 (status code 201)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "deleteBooking",
        summary = "予約キャンセルAPI",
        responses = {
            @ApiResponse(responseCode = "201", description = "予約キャンセル成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DeleteBookingResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/admin/deleteBooking",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<DeleteBookingResponse> deleteBooking(
        @Parameter(name = "DeleteBookingRequest", description = "", required = true) @Valid @RequestBody DeleteBookingRequest deleteBookingRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"success\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /api/v1/admin/deleteSchedule : スケジュール削除API
     *
     * @param deleteScheduleRequest  (required)
     * @return スケジュール登録成功 (status code 201)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "deleteSchedule",
        summary = "スケジュール削除API",
        responses = {
            @ApiResponse(responseCode = "201", description = "スケジュール登録成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DeleteScheduleResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/admin/deleteSchedule",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<DeleteScheduleResponse> deleteSchedule(
        @Parameter(name = "DeleteScheduleRequest", description = "", required = true) @Valid @RequestBody DeleteScheduleRequest deleteScheduleRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"success\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /api/v1/admin/deleteScheduleTemplate : 定期スケジュール削除API
     *
     * @param deleteScheduleTemplateRequest  (required)
     * @return 定期スケジュール登録成功 (status code 201)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "deleteScheduleTemplate",
        summary = "定期スケジュール削除API",
        responses = {
            @ApiResponse(responseCode = "201", description = "定期スケジュール登録成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DeleteScheduleTemplateResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/admin/deleteScheduleTemplate",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<DeleteScheduleTemplateResponse> deleteScheduleTemplate(
        @Parameter(name = "DeleteScheduleTemplateRequest", description = "", required = true) @Valid @RequestBody DeleteScheduleTemplateRequest deleteScheduleTemplateRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"success\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/v1/getAirports : 空港検索API
     *
     * @param getAirportsRequest  (required)
     * @return 航空機検索成功 (status code 200)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "getAirports",
        summary = "空港検索API",
        responses = {
            @ApiResponse(responseCode = "200", description = "航空機検索成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetAirportsResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/getAirports",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<GetAirportsResponse> getAirports(
        @Parameter(name = "GetAirportsRequest", description = "", required = true) @Valid @RequestBody GetAirportsRequest getAirportsRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"airportList\" : [ { \"country\" : \"country\", \"city\" : \"city\", \"airportId\" : \"airportId\", \"airportNameEn\" : \"airportNameEn\", \"airportNameKo\" : \"airportNameKo\" }, { \"country\" : \"country\", \"city\" : \"city\", \"airportId\" : \"airportId\", \"airportNameEn\" : \"airportNameEn\", \"airportNameKo\" : \"airportNameKo\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/v1/getFlights : 便一覧検索API
     *
     * @param getFlightsRequest  (required)
     * @return 便一覧検索成功 (status code 200)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "getFlights",
        summary = "便一覧検索API",
        responses = {
            @ApiResponse(responseCode = "200", description = "便一覧検索成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetFlightsResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/getFlights",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<GetFlightsResponse> getFlights(
        @Parameter(name = "GetFlightsRequest", description = "", required = true) @Valid @RequestBody GetFlightsRequest getFlightsRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"FlightsList\" : [ { \"aircraftName\" : \"aircraftName\", \"aircraftId\" : \"aircraftId\", \"price\" : 6, \"arrivalAirportId\" : \"arrivalAirportId\", \"arrivalDatetime\" : \"2000-01-23T04:56:07.000+00:00\", \"departureDatetime\" : \"2000-01-23T04:56:07.000+00:00\", \"scheduleId\" : 0, \"departureAirportId\" : \"departureAirportId\" }, { \"aircraftName\" : \"aircraftName\", \"aircraftId\" : \"aircraftId\", \"price\" : 6, \"arrivalAirportId\" : \"arrivalAirportId\", \"arrivalDatetime\" : \"2000-01-23T04:56:07.000+00:00\", \"departureDatetime\" : \"2000-01-23T04:56:07.000+00:00\", \"scheduleId\" : 0, \"departureAirportId\" : \"departureAirportId\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/v1/getSeats : 座席検索API
     *
     * @param getSeatsRequest  (required)
     * @return 座席検索成功 (status code 200)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "getSeats",
        summary = "座席検索API",
        responses = {
            @ApiResponse(responseCode = "200", description = "座席検索成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetSeatsResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/getSeats",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<GetSeatsResponse> getSeats(
        @Parameter(name = "GetSeatsRequest", description = "", required = true) @Valid @RequestBody GetSeatsRequest getSeatsRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"seatList\" : [ { \"scheduledSeatNo\" : 6, \"seatName\" : \"seatName\", \"status\" : \"status\" }, { \"scheduledSeatNo\" : 6, \"seatName\" : \"seatName\", \"status\" : \"status\" } ], \"scheduleId\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /api/v1/login : ログインAPI
     *
     * @param loginRequest  (required)
     * @return ログイン成功 (status code 201)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "login",
        summary = "ログインAPI",
        responses = {
            @ApiResponse(responseCode = "201", description = "ログイン成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LoginResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/login",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<LoginResponse> login(
        @Parameter(name = "LoginRequest", description = "", required = true) @Valid @RequestBody LoginRequest loginRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"success\" : true, \"accessToken\" : \"accessToken\", \"userName\" : \"userName\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/v1/admin/searchAircraft : 航空機検索API
     *
     * @param searchAircraftRequest  (required)
     * @return 航空機検索成功 (status code 200)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "searchAircraft",
        summary = "航空機検索API",
        responses = {
            @ApiResponse(responseCode = "200", description = "航空機検索成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SearchAircraftResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/admin/searchAircraft",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<SearchAircraftResponse> searchAircraft(
        @Parameter(name = "SearchAircraftRequest", description = "", required = true) @Valid @RequestBody SearchAircraftRequest searchAircraftRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"aircraftList\" : [ { \"aircraftName\" : \"Boeing-777\", \"aircraftId\" : \"SEO123\", \"rowCount\" : 0, \"columnCount\" : 6 }, { \"aircraftName\" : \"Boeing-777\", \"aircraftId\" : \"SEO123\", \"rowCount\" : 0, \"columnCount\" : 6 } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/v1/searchBooking : 予約検索API
     *
     * @param searchBookingRequest  (required)
     * @return 予約検索成功 (status code 200)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "searchBooking",
        summary = "予約検索API",
        responses = {
            @ApiResponse(responseCode = "200", description = "予約検索成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SearchBookingResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/searchBooking",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<SearchBookingResponse> searchBooking(
        @Parameter(name = "SearchBookingRequest", description = "", required = true) @Valid @RequestBody SearchBookingRequest searchBookingRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"bookingList\" : [ { \"totalPrice\" : 5, \"passengerCount\" : 5, \"arrivalDatetime\" : \"2000-01-23T04:56:07.000+00:00\", \"departureDatetime\" : \"2000-01-23T04:56:07.000+00:00\", \"userName\" : \"userName\", \"userId\" : 6, \"seats\" : [ { \"seat\" : \"seat\", \"name\" : \"name\" }, { \"seat\" : \"seat\", \"name\" : \"name\" } ], \"bookingId\" : 0, \"aircraftId\" : \"aircraftId\", \"arrivalAirportId\" : \"arrivalAirportId\", \"bookedTime\" : \"2000-01-23T04:56:07.000+00:00\", \"scheduleId\" : 1, \"departureAirportId\" : \"departureAirportId\", \"status\" : \"status\" }, { \"totalPrice\" : 5, \"passengerCount\" : 5, \"arrivalDatetime\" : \"2000-01-23T04:56:07.000+00:00\", \"departureDatetime\" : \"2000-01-23T04:56:07.000+00:00\", \"userName\" : \"userName\", \"userId\" : 6, \"seats\" : [ { \"seat\" : \"seat\", \"name\" : \"name\" }, { \"seat\" : \"seat\", \"name\" : \"name\" } ], \"bookingId\" : 0, \"aircraftId\" : \"aircraftId\", \"arrivalAirportId\" : \"arrivalAirportId\", \"bookedTime\" : \"2000-01-23T04:56:07.000+00:00\", \"scheduleId\" : 1, \"departureAirportId\" : \"departureAirportId\", \"status\" : \"status\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/v1/admin/searchSchedule : スケジュール検索API
     *
     * @param searchScheduleRequest  (required)
     * @return スケジュール検索成功 (status code 200)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "searchSchedule",
        summary = "スケジュール検索API",
        responses = {
            @ApiResponse(responseCode = "200", description = "スケジュール検索成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SearchScheduleResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/admin/searchSchedule",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<SearchScheduleResponse> searchSchedule(
        @Parameter(name = "SearchScheduleRequest", description = "", required = true) @Valid @RequestBody SearchScheduleRequest searchScheduleRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"scheduleList\" : [ { \"aircraftId\" : \"aircraftId\", \"arrivalAirportId\" : \"arrivalAirportId\", \"arrivalDatetime\" : \"2000-01-23T04:56:07.000+00:00\", \"departureDatetime\" : \"2000-01-23T04:56:07.000+00:00\", \"templateId\" : 6, \"scheduleId\" : 0, \"departureAirportId\" : \"departureAirportId\", \"status\" : \"status\" }, { \"aircraftId\" : \"aircraftId\", \"arrivalAirportId\" : \"arrivalAirportId\", \"arrivalDatetime\" : \"2000-01-23T04:56:07.000+00:00\", \"departureDatetime\" : \"2000-01-23T04:56:07.000+00:00\", \"templateId\" : 6, \"scheduleId\" : 0, \"departureAirportId\" : \"departureAirportId\", \"status\" : \"status\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/v1/admin/searchScheduleTemplate : 定期スケジュール検索API
     *
     * @param searchScheduleTemplateRequest  (required)
     * @return 定期スケジュール検索成功 (status code 200)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "searchScheduleTemplate",
        summary = "定期スケジュール検索API",
        responses = {
            @ApiResponse(responseCode = "200", description = "定期スケジュール検索成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SearchScheduleTemplateResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/admin/searchScheduleTemplate",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<SearchScheduleTemplateResponse> searchScheduleTemplate(
        @Parameter(name = "SearchScheduleTemplateRequest", description = "", required = true) @Valid @RequestBody SearchScheduleTemplateRequest searchScheduleTemplateRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"scheduleTemplateList\" : [ { \"departureTime\" : \"departureTime\", \"aircraftId\" : \"aircraftId\", \"endDate\" : \"2000-01-23\", \"arrivalTime\" : \"arrivalTime\", \"price\" : 6, \"arrivalAirportId\" : \"arrivalAirportId\", \"templateId\" : 0, \"daysOfWeek\" : { \"thu\" : true, \"tue\" : true, \"wed\" : true, \"sat\" : true, \"fri\" : true, \"mon\" : true, \"sun\" : true }, \"departureAirportId\" : \"departureAirportId\", \"startDate\" : \"2000-01-23\" }, { \"departureTime\" : \"departureTime\", \"aircraftId\" : \"aircraftId\", \"endDate\" : \"2000-01-23\", \"arrivalTime\" : \"arrivalTime\", \"price\" : 6, \"arrivalAirportId\" : \"arrivalAirportId\", \"templateId\" : 0, \"daysOfWeek\" : { \"thu\" : true, \"tue\" : true, \"wed\" : true, \"sat\" : true, \"fri\" : true, \"mon\" : true, \"sun\" : true }, \"departureAirportId\" : \"departureAirportId\", \"startDate\" : \"2000-01-23\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /api/v1/admin/updateAircraft : 航空機更新API
     *
     * @param updateAircraftRequest  (required)
     * @return 航空機更新成功 (status code 201)
     *         or 不正なリクエスト（パラメータ欠落、バリデーション失敗など） (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "updateAircraft",
        summary = "航空機更新API",
        responses = {
            @ApiResponse(responseCode = "201", description = "航空機更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UpdateAircraftResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "不正なリクエスト（パラメータ欠落、バリデーション失敗など）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/admin/updateAircraft",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<UpdateAircraftResponse> updateAircraft(
        @Parameter(name = "UpdateAircraftRequest", description = "", required = true) @Valid @RequestBody UpdateAircraftRequest updateAircraftRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"success\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
