package airlineReservation.infra.mapper;

import airlineReservation.infra.entity.Aircraft;
import airlineReservation.infra.entity.AircraftExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AircraftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircrafts
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    long countByExample(AircraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircrafts
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int deleteByExample(AircraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircrafts
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int deleteByPrimaryKey(String aircraftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircrafts
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int insert(Aircraft row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircrafts
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int insertSelective(Aircraft row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircrafts
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    List<Aircraft> selectByExample(AircraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircrafts
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    Aircraft selectByPrimaryKey(String aircraftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircrafts
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByExampleSelective(@Param("row") Aircraft row, @Param("example") AircraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircrafts
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByExample(@Param("row") Aircraft row, @Param("example") AircraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircrafts
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByPrimaryKeySelective(Aircraft row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircrafts
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByPrimaryKey(Aircraft row);
}