package airlineReservation.infra.mapper;

import airlineReservation.domain.entity.Airport;
import airlineReservation.domain.entity.AirportExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AirportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table airports
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    long countByExample(AirportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table airports
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int deleteByExample(AirportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table airports
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int deleteByPrimaryKey(String airportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table airports
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int insert(Airport row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table airports
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int insertSelective(Airport row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table airports
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    List<Airport> selectByExample(AirportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table airports
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    Airport selectByPrimaryKey(String airportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table airports
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int updateByExampleSelective(@Param("row") Airport row, @Param("example") AirportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table airports
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int updateByExample(@Param("row") Airport row, @Param("example") AirportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table airports
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int updateByPrimaryKeySelective(Airport row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table airports
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int updateByPrimaryKey(Airport row);
}