package airlineReservation.infra.mapper;

import airlineReservation.domain.entity.Booking;
import airlineReservation.domain.entity.BookingExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BookingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookings
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    long countByExample(BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookings
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int deleteByExample(BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookings
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int deleteByPrimaryKey(Long bookingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookings
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int insert(Booking row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookings
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int insertSelective(Booking row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookings
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    List<Booking> selectByExample(BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookings
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    Booking selectByPrimaryKey(Long bookingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookings
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int updateByExampleSelective(@Param("row") Booking row, @Param("example") BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookings
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int updateByExample(@Param("row") Booking row, @Param("example") BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookings
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int updateByPrimaryKeySelective(Booking row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookings
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int updateByPrimaryKey(Booking row);
}