package airlineReservation.infra.mapper;

import airlineReservation.infra.entity.PassengerDetail;
import airlineReservation.infra.entity.PassengerDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PassengerDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger_details
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    long countByExample(PassengerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger_details
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int deleteByExample(PassengerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger_details
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int deleteByPrimaryKey(Integer passengerDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger_details
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int insert(PassengerDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger_details
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int insertSelective(PassengerDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger_details
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    List<PassengerDetail> selectByExample(PassengerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger_details
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    PassengerDetail selectByPrimaryKey(Integer passengerDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger_details
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByExampleSelective(@Param("row") PassengerDetail row, @Param("example") PassengerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger_details
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByExample(@Param("row") PassengerDetail row, @Param("example") PassengerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger_details
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByPrimaryKeySelective(PassengerDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger_details
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByPrimaryKey(PassengerDetail row);
}