package airlineReservation.infra.mapper;

import airlineReservation.infra.entity.Schedule;
import airlineReservation.infra.entity.ScheduleExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    long countByExample(ScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int deleteByExample(ScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int deleteByPrimaryKey(Integer scheduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int insert(Schedule row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int insertSelective(Schedule row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    List<Schedule> selectByExample(ScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    Schedule selectByPrimaryKey(Integer scheduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByExampleSelective(@Param("row") Schedule row, @Param("example") ScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByExample(@Param("row") Schedule row, @Param("example") ScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByPrimaryKeySelective(Schedule row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByPrimaryKey(Schedule row);
}