package airlineReservation.infra.mapper;

import airlineReservation.infra.entity.ScheduleTemplates;
import airlineReservation.infra.entity.ScheduleTemplatesExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ScheduleTemplatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    long countByExample(ScheduleTemplatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int deleteByExample(ScheduleTemplatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int deleteByPrimaryKey(Integer templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int insert(ScheduleTemplates row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int insertSelective(ScheduleTemplates row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    List<ScheduleTemplates> selectByExample(ScheduleTemplatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    ScheduleTemplates selectByPrimaryKey(Integer templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByExampleSelective(@Param("row") ScheduleTemplates row, @Param("example") ScheduleTemplatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByExample(@Param("row") ScheduleTemplates row, @Param("example") ScheduleTemplatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByPrimaryKeySelective(ScheduleTemplates row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByPrimaryKey(ScheduleTemplates row);
}