package airlineReservation.infra.mapper;

import airlineReservation.infra.entity.ScheduleSeat;
import airlineReservation.infra.entity.ScheduleSeatExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ScheduleSeatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_seats
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    long countByExample(ScheduleSeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_seats
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int deleteByExample(ScheduleSeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_seats
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int deleteByPrimaryKey(Integer scheduledSeatNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_seats
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int insert(ScheduleSeat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_seats
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int insertSelective(ScheduleSeat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_seats
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    List<ScheduleSeat> selectByExample(ScheduleSeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_seats
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    ScheduleSeat selectByPrimaryKey(Integer scheduledSeatNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_seats
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByExampleSelective(@Param("row") ScheduleSeat row, @Param("example") ScheduleSeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_seats
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByExample(@Param("row") ScheduleSeat row, @Param("example") ScheduleSeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_seats
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByPrimaryKeySelective(ScheduleSeat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_seats
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    int updateByPrimaryKey(ScheduleSeat row);
}