package airlineReservation.infra.mapper;

import airlineReservation.domain.entity.Seat;
import airlineReservation.domain.entity.SeatExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SeatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seats
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    long countByExample(SeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seats
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int deleteByExample(SeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seats
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int deleteByPrimaryKey(Long seatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seats
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int insert(Seat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seats
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int insertSelective(Seat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seats
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    List<Seat> selectByExample(SeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seats
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    Seat selectByPrimaryKey(Long seatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seats
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int updateByExampleSelective(@Param("row") Seat row, @Param("example") SeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seats
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int updateByExample(@Param("row") Seat row, @Param("example") SeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seats
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int updateByPrimaryKeySelective(Seat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seats
     *
     * @mbg.generated Mon Jul 20 23:08:38 JST 2026
     */
    int updateByPrimaryKey(Seat row);
}