package airlineReservation.infra.entity;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   空港
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table airports
 */
public class Airport {
    /**
     * Database Column Remarks:
     *   空港コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.airport_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private String airportId;

    /**
     * Database Column Remarks:
     *   空港韓国語名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.airport_name_ko
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private String airportNameKo;

    /**
     * Database Column Remarks:
     *   空港英語名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.airport_name_en
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private String airportNameEn;

    /**
     * Database Column Remarks:
     *   国名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.country
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private String country;

    /**
     * Database Column Remarks:
     *   都市名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.city
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private String city;

    /**
     * Database Column Remarks:
     *   運休フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.is_deleted
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Boolean isDeleted;

    /**
     * Database Column Remarks:
     *   初回登録ユーザーID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.created_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer createdBy;

    /**
     * Database Column Remarks:
     *   初回登録日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.created_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     * Database Column Remarks:
     *   最終更新ユーザーID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.updated_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer updatedBy;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airports.updated_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.airport_id
     *
     * @return the value of airports.airport_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public String getAirportId() {
        return airportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.airport_id
     *
     * @param airportId the value for airports.airport_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setAirportId(String airportId) {
        this.airportId = airportId == null ? null : airportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.airport_name_ko
     *
     * @return the value of airports.airport_name_ko
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public String getAirportNameKo() {
        return airportNameKo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.airport_name_ko
     *
     * @param airportNameKo the value for airports.airport_name_ko
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setAirportNameKo(String airportNameKo) {
        this.airportNameKo = airportNameKo == null ? null : airportNameKo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.airport_name_en
     *
     * @return the value of airports.airport_name_en
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public String getAirportNameEn() {
        return airportNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.airport_name_en
     *
     * @param airportNameEn the value for airports.airport_name_en
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setAirportNameEn(String airportNameEn) {
        this.airportNameEn = airportNameEn == null ? null : airportNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.country
     *
     * @return the value of airports.country
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.country
     *
     * @param country the value for airports.country
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.city
     *
     * @return the value of airports.city
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.city
     *
     * @param city the value for airports.city
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.is_deleted
     *
     * @return the value of airports.is_deleted
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.is_deleted
     *
     * @param isDeleted the value for airports.is_deleted
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.created_by
     *
     * @return the value of airports.created_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.created_by
     *
     * @param createdBy the value for airports.created_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.created_at
     *
     * @return the value of airports.created_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.created_at
     *
     * @param createdAt the value for airports.created_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.updated_by
     *
     * @return the value of airports.updated_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.updated_by
     *
     * @param updatedBy the value for airports.updated_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column airports.updated_at
     *
     * @return the value of airports.updated_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column airports.updated_at
     *
     * @param updatedAt the value for airports.updated_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}