package airlineReservation.infra.entity;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   搭乗者予約詳細
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table passenger_details
 */
public class PassengerDetail {
    /**
     * Database Column Remarks:
     *   搭乗者詳細連番
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger_details.passenger_detail_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer passengerDetailId;

    /**
     * Database Column Remarks:
     *   予約連番
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger_details.booking_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer bookingId;

    /**
     * Database Column Remarks:
     *   搭乗者氏名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger_details.passenger_name
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private String passengerName;

    /**
     * Database Column Remarks:
     *   スケジュール別座席ステータス番号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger_details.schedule_seat_no
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer scheduleSeatNo;

    /**
     * Database Column Remarks:
     *   削除フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger_details.is_deleted
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Boolean isDeleted;

    /**
     * Database Column Remarks:
     *   初回登録ユーザーID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger_details.created_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer createdBy;

    /**
     * Database Column Remarks:
     *   初回登録日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger_details.created_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     * Database Column Remarks:
     *   最終更新ユーザーID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger_details.updated_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer updatedBy;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger_details.updated_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger_details.passenger_detail_id
     *
     * @return the value of passenger_details.passenger_detail_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getPassengerDetailId() {
        return passengerDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger_details.passenger_detail_id
     *
     * @param passengerDetailId the value for passenger_details.passenger_detail_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setPassengerDetailId(Integer passengerDetailId) {
        this.passengerDetailId = passengerDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger_details.booking_id
     *
     * @return the value of passenger_details.booking_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getBookingId() {
        return bookingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger_details.booking_id
     *
     * @param bookingId the value for passenger_details.booking_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setBookingId(Integer bookingId) {
        this.bookingId = bookingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger_details.passenger_name
     *
     * @return the value of passenger_details.passenger_name
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public String getPassengerName() {
        return passengerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger_details.passenger_name
     *
     * @param passengerName the value for passenger_details.passenger_name
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setPassengerName(String passengerName) {
        this.passengerName = passengerName == null ? null : passengerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger_details.schedule_seat_no
     *
     * @return the value of passenger_details.schedule_seat_no
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getScheduleSeatNo() {
        return scheduleSeatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger_details.schedule_seat_no
     *
     * @param scheduleSeatNo the value for passenger_details.schedule_seat_no
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setScheduleSeatNo(Integer scheduleSeatNo) {
        this.scheduleSeatNo = scheduleSeatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger_details.is_deleted
     *
     * @return the value of passenger_details.is_deleted
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger_details.is_deleted
     *
     * @param isDeleted the value for passenger_details.is_deleted
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger_details.created_by
     *
     * @return the value of passenger_details.created_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger_details.created_by
     *
     * @param createdBy the value for passenger_details.created_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger_details.created_at
     *
     * @return the value of passenger_details.created_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger_details.created_at
     *
     * @param createdAt the value for passenger_details.created_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger_details.updated_by
     *
     * @return the value of passenger_details.updated_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger_details.updated_by
     *
     * @param updatedBy the value for passenger_details.updated_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger_details.updated_at
     *
     * @return the value of passenger_details.updated_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger_details.updated_at
     *
     * @param updatedAt the value for passenger_details.updated_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}