package airlineReservation.infra.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

/**
 * Database Table Remarks:
 *   定期運航テンプレートマスタ
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table schedule_templates
 */
public class ScheduleTemplates {
    /**
     * Database Column Remarks:
     *   テンプレートID (PK)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.template_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer templateId;

    /**
     * Database Column Remarks:
     *   航空機ID（FK）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.aircraft_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private String aircraftId;

    /**
     * Database Column Remarks:
     *   出発空港ID（FK）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.departure_airport_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private String departureAirportId;

    /**
     * Database Column Remarks:
     *   到着空港ID（FK）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.arrival_airport_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private String arrivalAirportId;

    /**
     * Database Column Remarks:
     *   定期運航開始日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.start_date
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private LocalDate startDate;

    /**
     * Database Column Remarks:
     *   定期運航終了日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.end_date
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private LocalDate endDate;

    /**
     * Database Column Remarks:
     *   出発時刻
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.departure_time
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private LocalTime departureTime;

    /**
     * Database Column Remarks:
     *   到着時刻
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.arrival_time
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private LocalTime arrivalTime;

    /**
     * Database Column Remarks:
     *   月曜日運航フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.is_monday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Boolean isMonday;

    /**
     * Database Column Remarks:
     *   火曜日運航フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.is_tuesday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Boolean isTuesday;

    /**
     * Database Column Remarks:
     *   水曜日運航フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.is_wednesday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Boolean isWednesday;

    /**
     * Database Column Remarks:
     *   木曜日運航フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.is_thursday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Boolean isThursday;

    /**
     * Database Column Remarks:
     *   金曜日運航フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.is_friday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Boolean isFriday;

    /**
     * Database Column Remarks:
     *   土曜日運航フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.is_saturday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Boolean isSaturday;

    /**
     * Database Column Remarks:
     *   日曜日運航フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.is_sunday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Boolean isSunday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.created_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.created_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.updated_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.updated_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     * Database Column Remarks:
     *   料金
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_templates.price
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.template_id
     *
     * @return the value of schedule_templates.template_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.template_id
     *
     * @param templateId the value for schedule_templates.template_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.aircraft_id
     *
     * @return the value of schedule_templates.aircraft_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public String getAircraftId() {
        return aircraftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.aircraft_id
     *
     * @param aircraftId the value for schedule_templates.aircraft_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setAircraftId(String aircraftId) {
        this.aircraftId = aircraftId == null ? null : aircraftId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.departure_airport_id
     *
     * @return the value of schedule_templates.departure_airport_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public String getDepartureAirportId() {
        return departureAirportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.departure_airport_id
     *
     * @param departureAirportId the value for schedule_templates.departure_airport_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setDepartureAirportId(String departureAirportId) {
        this.departureAirportId = departureAirportId == null ? null : departureAirportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.arrival_airport_id
     *
     * @return the value of schedule_templates.arrival_airport_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public String getArrivalAirportId() {
        return arrivalAirportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.arrival_airport_id
     *
     * @param arrivalAirportId the value for schedule_templates.arrival_airport_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setArrivalAirportId(String arrivalAirportId) {
        this.arrivalAirportId = arrivalAirportId == null ? null : arrivalAirportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.start_date
     *
     * @return the value of schedule_templates.start_date
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public LocalDate getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.start_date
     *
     * @param startDate the value for schedule_templates.start_date
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.end_date
     *
     * @return the value of schedule_templates.end_date
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public LocalDate getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.end_date
     *
     * @param endDate the value for schedule_templates.end_date
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.departure_time
     *
     * @return the value of schedule_templates.departure_time
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public LocalTime getDepartureTime() {
        return departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.departure_time
     *
     * @param departureTime the value for schedule_templates.departure_time
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setDepartureTime(LocalTime departureTime) {
        this.departureTime = departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.arrival_time
     *
     * @return the value of schedule_templates.arrival_time
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public LocalTime getArrivalTime() {
        return arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.arrival_time
     *
     * @param arrivalTime the value for schedule_templates.arrival_time
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setArrivalTime(LocalTime arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.is_monday
     *
     * @return the value of schedule_templates.is_monday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Boolean getIsMonday() {
        return isMonday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.is_monday
     *
     * @param isMonday the value for schedule_templates.is_monday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setIsMonday(Boolean isMonday) {
        this.isMonday = isMonday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.is_tuesday
     *
     * @return the value of schedule_templates.is_tuesday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Boolean getIsTuesday() {
        return isTuesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.is_tuesday
     *
     * @param isTuesday the value for schedule_templates.is_tuesday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setIsTuesday(Boolean isTuesday) {
        this.isTuesday = isTuesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.is_wednesday
     *
     * @return the value of schedule_templates.is_wednesday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Boolean getIsWednesday() {
        return isWednesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.is_wednesday
     *
     * @param isWednesday the value for schedule_templates.is_wednesday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setIsWednesday(Boolean isWednesday) {
        this.isWednesday = isWednesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.is_thursday
     *
     * @return the value of schedule_templates.is_thursday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Boolean getIsThursday() {
        return isThursday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.is_thursday
     *
     * @param isThursday the value for schedule_templates.is_thursday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setIsThursday(Boolean isThursday) {
        this.isThursday = isThursday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.is_friday
     *
     * @return the value of schedule_templates.is_friday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Boolean getIsFriday() {
        return isFriday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.is_friday
     *
     * @param isFriday the value for schedule_templates.is_friday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setIsFriday(Boolean isFriday) {
        this.isFriday = isFriday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.is_saturday
     *
     * @return the value of schedule_templates.is_saturday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Boolean getIsSaturday() {
        return isSaturday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.is_saturday
     *
     * @param isSaturday the value for schedule_templates.is_saturday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setIsSaturday(Boolean isSaturday) {
        this.isSaturday = isSaturday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.is_sunday
     *
     * @return the value of schedule_templates.is_sunday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Boolean getIsSunday() {
        return isSunday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.is_sunday
     *
     * @param isSunday the value for schedule_templates.is_sunday
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setIsSunday(Boolean isSunday) {
        this.isSunday = isSunday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.created_by
     *
     * @return the value of schedule_templates.created_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.created_by
     *
     * @param createdBy the value for schedule_templates.created_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.created_at
     *
     * @return the value of schedule_templates.created_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.created_at
     *
     * @param createdAt the value for schedule_templates.created_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.updated_by
     *
     * @return the value of schedule_templates.updated_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.updated_by
     *
     * @param updatedBy the value for schedule_templates.updated_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.updated_at
     *
     * @return the value of schedule_templates.updated_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.updated_at
     *
     * @param updatedAt the value for schedule_templates.updated_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_templates.price
     *
     * @return the value of schedule_templates.price
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_templates.price
     *
     * @param price the value for schedule_templates.price
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setPrice(Integer price) {
        this.price = price;
    }
}