package airlineReservation.infra.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

public class ScheduleTemplatesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public ScheduleTemplatesExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTemplateIdIsNull() {
            addCriterion("template_id is null");
            return (Criteria) this;
        }

        public Criteria andTemplateIdIsNotNull() {
            addCriterion("template_id is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateIdEqualTo(Integer value) {
            addCriterion("template_id =", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdNotEqualTo(Integer value) {
            addCriterion("template_id <>", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdGreaterThan(Integer value) {
            addCriterion("template_id >", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("template_id >=", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdLessThan(Integer value) {
            addCriterion("template_id <", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdLessThanOrEqualTo(Integer value) {
            addCriterion("template_id <=", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdIn(List<Integer> values) {
            addCriterion("template_id in", values, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdNotIn(List<Integer> values) {
            addCriterion("template_id not in", values, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdBetween(Integer value1, Integer value2) {
            addCriterion("template_id between", value1, value2, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdNotBetween(Integer value1, Integer value2) {
            addCriterion("template_id not between", value1, value2, "templateId");
            return (Criteria) this;
        }

        public Criteria andAircraftIdIsNull() {
            addCriterion("aircraft_id is null");
            return (Criteria) this;
        }

        public Criteria andAircraftIdIsNotNull() {
            addCriterion("aircraft_id is not null");
            return (Criteria) this;
        }

        public Criteria andAircraftIdEqualTo(String value) {
            addCriterion("aircraft_id =", value, "aircraftId");
            return (Criteria) this;
        }

        public Criteria andAircraftIdNotEqualTo(String value) {
            addCriterion("aircraft_id <>", value, "aircraftId");
            return (Criteria) this;
        }

        public Criteria andAircraftIdGreaterThan(String value) {
            addCriterion("aircraft_id >", value, "aircraftId");
            return (Criteria) this;
        }

        public Criteria andAircraftIdGreaterThanOrEqualTo(String value) {
            addCriterion("aircraft_id >=", value, "aircraftId");
            return (Criteria) this;
        }

        public Criteria andAircraftIdLessThan(String value) {
            addCriterion("aircraft_id <", value, "aircraftId");
            return (Criteria) this;
        }

        public Criteria andAircraftIdLessThanOrEqualTo(String value) {
            addCriterion("aircraft_id <=", value, "aircraftId");
            return (Criteria) this;
        }

        public Criteria andAircraftIdLike(String value) {
            addCriterion("aircraft_id like", value, "aircraftId");
            return (Criteria) this;
        }

        public Criteria andAircraftIdNotLike(String value) {
            addCriterion("aircraft_id not like", value, "aircraftId");
            return (Criteria) this;
        }

        public Criteria andAircraftIdIn(List<String> values) {
            addCriterion("aircraft_id in", values, "aircraftId");
            return (Criteria) this;
        }

        public Criteria andAircraftIdNotIn(List<String> values) {
            addCriterion("aircraft_id not in", values, "aircraftId");
            return (Criteria) this;
        }

        public Criteria andAircraftIdBetween(String value1, String value2) {
            addCriterion("aircraft_id between", value1, value2, "aircraftId");
            return (Criteria) this;
        }

        public Criteria andAircraftIdNotBetween(String value1, String value2) {
            addCriterion("aircraft_id not between", value1, value2, "aircraftId");
            return (Criteria) this;
        }

        public Criteria andDepartureAirportIdIsNull() {
            addCriterion("departure_airport_id is null");
            return (Criteria) this;
        }

        public Criteria andDepartureAirportIdIsNotNull() {
            addCriterion("departure_airport_id is not null");
            return (Criteria) this;
        }

        public Criteria andDepartureAirportIdEqualTo(String value) {
            addCriterion("departure_airport_id =", value, "departureAirportId");
            return (Criteria) this;
        }

        public Criteria andDepartureAirportIdNotEqualTo(String value) {
            addCriterion("departure_airport_id <>", value, "departureAirportId");
            return (Criteria) this;
        }

        public Criteria andDepartureAirportIdGreaterThan(String value) {
            addCriterion("departure_airport_id >", value, "departureAirportId");
            return (Criteria) this;
        }

        public Criteria andDepartureAirportIdGreaterThanOrEqualTo(String value) {
            addCriterion("departure_airport_id >=", value, "departureAirportId");
            return (Criteria) this;
        }

        public Criteria andDepartureAirportIdLessThan(String value) {
            addCriterion("departure_airport_id <", value, "departureAirportId");
            return (Criteria) this;
        }

        public Criteria andDepartureAirportIdLessThanOrEqualTo(String value) {
            addCriterion("departure_airport_id <=", value, "departureAirportId");
            return (Criteria) this;
        }

        public Criteria andDepartureAirportIdLike(String value) {
            addCriterion("departure_airport_id like", value, "departureAirportId");
            return (Criteria) this;
        }

        public Criteria andDepartureAirportIdNotLike(String value) {
            addCriterion("departure_airport_id not like", value, "departureAirportId");
            return (Criteria) this;
        }

        public Criteria andDepartureAirportIdIn(List<String> values) {
            addCriterion("departure_airport_id in", values, "departureAirportId");
            return (Criteria) this;
        }

        public Criteria andDepartureAirportIdNotIn(List<String> values) {
            addCriterion("departure_airport_id not in", values, "departureAirportId");
            return (Criteria) this;
        }

        public Criteria andDepartureAirportIdBetween(String value1, String value2) {
            addCriterion("departure_airport_id between", value1, value2, "departureAirportId");
            return (Criteria) this;
        }

        public Criteria andDepartureAirportIdNotBetween(String value1, String value2) {
            addCriterion("departure_airport_id not between", value1, value2, "departureAirportId");
            return (Criteria) this;
        }

        public Criteria andArrivalAirportIdIsNull() {
            addCriterion("arrival_airport_id is null");
            return (Criteria) this;
        }

        public Criteria andArrivalAirportIdIsNotNull() {
            addCriterion("arrival_airport_id is not null");
            return (Criteria) this;
        }

        public Criteria andArrivalAirportIdEqualTo(String value) {
            addCriterion("arrival_airport_id =", value, "arrivalAirportId");
            return (Criteria) this;
        }

        public Criteria andArrivalAirportIdNotEqualTo(String value) {
            addCriterion("arrival_airport_id <>", value, "arrivalAirportId");
            return (Criteria) this;
        }

        public Criteria andArrivalAirportIdGreaterThan(String value) {
            addCriterion("arrival_airport_id >", value, "arrivalAirportId");
            return (Criteria) this;
        }

        public Criteria andArrivalAirportIdGreaterThanOrEqualTo(String value) {
            addCriterion("arrival_airport_id >=", value, "arrivalAirportId");
            return (Criteria) this;
        }

        public Criteria andArrivalAirportIdLessThan(String value) {
            addCriterion("arrival_airport_id <", value, "arrivalAirportId");
            return (Criteria) this;
        }

        public Criteria andArrivalAirportIdLessThanOrEqualTo(String value) {
            addCriterion("arrival_airport_id <=", value, "arrivalAirportId");
            return (Criteria) this;
        }

        public Criteria andArrivalAirportIdLike(String value) {
            addCriterion("arrival_airport_id like", value, "arrivalAirportId");
            return (Criteria) this;
        }

        public Criteria andArrivalAirportIdNotLike(String value) {
            addCriterion("arrival_airport_id not like", value, "arrivalAirportId");
            return (Criteria) this;
        }

        public Criteria andArrivalAirportIdIn(List<String> values) {
            addCriterion("arrival_airport_id in", values, "arrivalAirportId");
            return (Criteria) this;
        }

        public Criteria andArrivalAirportIdNotIn(List<String> values) {
            addCriterion("arrival_airport_id not in", values, "arrivalAirportId");
            return (Criteria) this;
        }

        public Criteria andArrivalAirportIdBetween(String value1, String value2) {
            addCriterion("arrival_airport_id between", value1, value2, "arrivalAirportId");
            return (Criteria) this;
        }

        public Criteria andArrivalAirportIdNotBetween(String value1, String value2) {
            addCriterion("arrival_airport_id not between", value1, value2, "arrivalAirportId");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("start_date is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("start_date is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(LocalDate value) {
            addCriterion("start_date =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(LocalDate value) {
            addCriterion("start_date <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(LocalDate value) {
            addCriterion("start_date >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(LocalDate value) {
            addCriterion("start_date >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(LocalDate value) {
            addCriterion("start_date <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(LocalDate value) {
            addCriterion("start_date <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<LocalDate> values) {
            addCriterion("start_date in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<LocalDate> values) {
            addCriterion("start_date not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(LocalDate value1, LocalDate value2) {
            addCriterion("start_date between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(LocalDate value1, LocalDate value2) {
            addCriterion("start_date not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("end_date is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("end_date is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(LocalDate value) {
            addCriterion("end_date =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(LocalDate value) {
            addCriterion("end_date <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(LocalDate value) {
            addCriterion("end_date >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(LocalDate value) {
            addCriterion("end_date >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(LocalDate value) {
            addCriterion("end_date <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(LocalDate value) {
            addCriterion("end_date <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<LocalDate> values) {
            addCriterion("end_date in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<LocalDate> values) {
            addCriterion("end_date not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(LocalDate value1, LocalDate value2) {
            addCriterion("end_date between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(LocalDate value1, LocalDate value2) {
            addCriterion("end_date not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeIsNull() {
            addCriterion("departure_time is null");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeIsNotNull() {
            addCriterion("departure_time is not null");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeEqualTo(LocalTime value) {
            addCriterion("departure_time =", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeNotEqualTo(LocalTime value) {
            addCriterion("departure_time <>", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeGreaterThan(LocalTime value) {
            addCriterion("departure_time >", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeGreaterThanOrEqualTo(LocalTime value) {
            addCriterion("departure_time >=", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeLessThan(LocalTime value) {
            addCriterion("departure_time <", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeLessThanOrEqualTo(LocalTime value) {
            addCriterion("departure_time <=", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeIn(List<LocalTime> values) {
            addCriterion("departure_time in", values, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeNotIn(List<LocalTime> values) {
            addCriterion("departure_time not in", values, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeBetween(LocalTime value1, LocalTime value2) {
            addCriterion("departure_time between", value1, value2, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeNotBetween(LocalTime value1, LocalTime value2) {
            addCriterion("departure_time not between", value1, value2, "departureTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeIsNull() {
            addCriterion("arrival_time is null");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeIsNotNull() {
            addCriterion("arrival_time is not null");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeEqualTo(LocalTime value) {
            addCriterion("arrival_time =", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeNotEqualTo(LocalTime value) {
            addCriterion("arrival_time <>", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeGreaterThan(LocalTime value) {
            addCriterion("arrival_time >", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeGreaterThanOrEqualTo(LocalTime value) {
            addCriterion("arrival_time >=", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeLessThan(LocalTime value) {
            addCriterion("arrival_time <", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeLessThanOrEqualTo(LocalTime value) {
            addCriterion("arrival_time <=", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeIn(List<LocalTime> values) {
            addCriterion("arrival_time in", values, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeNotIn(List<LocalTime> values) {
            addCriterion("arrival_time not in", values, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeBetween(LocalTime value1, LocalTime value2) {
            addCriterion("arrival_time between", value1, value2, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeNotBetween(LocalTime value1, LocalTime value2) {
            addCriterion("arrival_time not between", value1, value2, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andIsMondayIsNull() {
            addCriterion("is_monday is null");
            return (Criteria) this;
        }

        public Criteria andIsMondayIsNotNull() {
            addCriterion("is_monday is not null");
            return (Criteria) this;
        }

        public Criteria andIsMondayEqualTo(Boolean value) {
            addCriterion("is_monday =", value, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayNotEqualTo(Boolean value) {
            addCriterion("is_monday <>", value, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayGreaterThan(Boolean value) {
            addCriterion("is_monday >", value, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_monday >=", value, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayLessThan(Boolean value) {
            addCriterion("is_monday <", value, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayLessThanOrEqualTo(Boolean value) {
            addCriterion("is_monday <=", value, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayIn(List<Boolean> values) {
            addCriterion("is_monday in", values, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayNotIn(List<Boolean> values) {
            addCriterion("is_monday not in", values, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayBetween(Boolean value1, Boolean value2) {
            addCriterion("is_monday between", value1, value2, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_monday not between", value1, value2, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayIsNull() {
            addCriterion("is_tuesday is null");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayIsNotNull() {
            addCriterion("is_tuesday is not null");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayEqualTo(Boolean value) {
            addCriterion("is_tuesday =", value, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayNotEqualTo(Boolean value) {
            addCriterion("is_tuesday <>", value, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayGreaterThan(Boolean value) {
            addCriterion("is_tuesday >", value, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_tuesday >=", value, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayLessThan(Boolean value) {
            addCriterion("is_tuesday <", value, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayLessThanOrEqualTo(Boolean value) {
            addCriterion("is_tuesday <=", value, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayIn(List<Boolean> values) {
            addCriterion("is_tuesday in", values, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayNotIn(List<Boolean> values) {
            addCriterion("is_tuesday not in", values, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayBetween(Boolean value1, Boolean value2) {
            addCriterion("is_tuesday between", value1, value2, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_tuesday not between", value1, value2, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayIsNull() {
            addCriterion("is_wednesday is null");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayIsNotNull() {
            addCriterion("is_wednesday is not null");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayEqualTo(Boolean value) {
            addCriterion("is_wednesday =", value, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayNotEqualTo(Boolean value) {
            addCriterion("is_wednesday <>", value, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayGreaterThan(Boolean value) {
            addCriterion("is_wednesday >", value, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_wednesday >=", value, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayLessThan(Boolean value) {
            addCriterion("is_wednesday <", value, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayLessThanOrEqualTo(Boolean value) {
            addCriterion("is_wednesday <=", value, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayIn(List<Boolean> values) {
            addCriterion("is_wednesday in", values, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayNotIn(List<Boolean> values) {
            addCriterion("is_wednesday not in", values, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayBetween(Boolean value1, Boolean value2) {
            addCriterion("is_wednesday between", value1, value2, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_wednesday not between", value1, value2, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayIsNull() {
            addCriterion("is_thursday is null");
            return (Criteria) this;
        }

        public Criteria andIsThursdayIsNotNull() {
            addCriterion("is_thursday is not null");
            return (Criteria) this;
        }

        public Criteria andIsThursdayEqualTo(Boolean value) {
            addCriterion("is_thursday =", value, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayNotEqualTo(Boolean value) {
            addCriterion("is_thursday <>", value, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayGreaterThan(Boolean value) {
            addCriterion("is_thursday >", value, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_thursday >=", value, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayLessThan(Boolean value) {
            addCriterion("is_thursday <", value, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayLessThanOrEqualTo(Boolean value) {
            addCriterion("is_thursday <=", value, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayIn(List<Boolean> values) {
            addCriterion("is_thursday in", values, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayNotIn(List<Boolean> values) {
            addCriterion("is_thursday not in", values, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayBetween(Boolean value1, Boolean value2) {
            addCriterion("is_thursday between", value1, value2, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_thursday not between", value1, value2, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsFridayIsNull() {
            addCriterion("is_friday is null");
            return (Criteria) this;
        }

        public Criteria andIsFridayIsNotNull() {
            addCriterion("is_friday is not null");
            return (Criteria) this;
        }

        public Criteria andIsFridayEqualTo(Boolean value) {
            addCriterion("is_friday =", value, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayNotEqualTo(Boolean value) {
            addCriterion("is_friday <>", value, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayGreaterThan(Boolean value) {
            addCriterion("is_friday >", value, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_friday >=", value, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayLessThan(Boolean value) {
            addCriterion("is_friday <", value, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayLessThanOrEqualTo(Boolean value) {
            addCriterion("is_friday <=", value, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayIn(List<Boolean> values) {
            addCriterion("is_friday in", values, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayNotIn(List<Boolean> values) {
            addCriterion("is_friday not in", values, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayBetween(Boolean value1, Boolean value2) {
            addCriterion("is_friday between", value1, value2, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_friday not between", value1, value2, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayIsNull() {
            addCriterion("is_saturday is null");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayIsNotNull() {
            addCriterion("is_saturday is not null");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayEqualTo(Boolean value) {
            addCriterion("is_saturday =", value, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayNotEqualTo(Boolean value) {
            addCriterion("is_saturday <>", value, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayGreaterThan(Boolean value) {
            addCriterion("is_saturday >", value, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_saturday >=", value, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayLessThan(Boolean value) {
            addCriterion("is_saturday <", value, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayLessThanOrEqualTo(Boolean value) {
            addCriterion("is_saturday <=", value, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayIn(List<Boolean> values) {
            addCriterion("is_saturday in", values, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayNotIn(List<Boolean> values) {
            addCriterion("is_saturday not in", values, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayBetween(Boolean value1, Boolean value2) {
            addCriterion("is_saturday between", value1, value2, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_saturday not between", value1, value2, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSundayIsNull() {
            addCriterion("is_sunday is null");
            return (Criteria) this;
        }

        public Criteria andIsSundayIsNotNull() {
            addCriterion("is_sunday is not null");
            return (Criteria) this;
        }

        public Criteria andIsSundayEqualTo(Boolean value) {
            addCriterion("is_sunday =", value, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayNotEqualTo(Boolean value) {
            addCriterion("is_sunday <>", value, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayGreaterThan(Boolean value) {
            addCriterion("is_sunday >", value, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_sunday >=", value, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayLessThan(Boolean value) {
            addCriterion("is_sunday <", value, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayLessThanOrEqualTo(Boolean value) {
            addCriterion("is_sunday <=", value, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayIn(List<Boolean> values) {
            addCriterion("is_sunday in", values, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayNotIn(List<Boolean> values) {
            addCriterion("is_sunday not in", values, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayBetween(Boolean value1, Boolean value2) {
            addCriterion("is_sunday between", value1, value2, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_sunday not between", value1, value2, "isSunday");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(Integer value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(Integer value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(Integer value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(Integer value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(Integer value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(Integer value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<Integer> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<Integer> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(Integer value1, Integer value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(Integer value1, Integer value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(LocalDateTime value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(LocalDateTime value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(LocalDateTime value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<LocalDateTime> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("updated_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("updated_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(Integer value) {
            addCriterion("updated_by =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(Integer value) {
            addCriterion("updated_by <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(Integer value) {
            addCriterion("updated_by >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(Integer value) {
            addCriterion("updated_by >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(Integer value) {
            addCriterion("updated_by <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(Integer value) {
            addCriterion("updated_by <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<Integer> values) {
            addCriterion("updated_by in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<Integer> values) {
            addCriterion("updated_by not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(Integer value1, Integer value2) {
            addCriterion("updated_by between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(Integer value1, Integer value2) {
            addCriterion("updated_by not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(LocalDateTime value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(LocalDateTime value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(LocalDateTime value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<LocalDateTime> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Integer value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Integer value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Integer value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Integer value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Integer value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Integer> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Integer> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Integer value1, Integer value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule_templates
     *
     * @mbg.generated do_not_delete_during_merge Sat Jul 25 18:49:07 JST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule_templates
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}