package airlineReservation.infra.entity;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   ユーザー種別
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_roles
 */
public class UserRole {
    /**
     * Database Column Remarks:
     *   権限コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.role_code
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer roleCode;

    /**
     * Database Column Remarks:
     *   権限名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.role_name
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private String roleName;

    /**
     * Database Column Remarks:
     *   初回登録ユーザーID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.created_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer createdBy;

    /**
     * Database Column Remarks:
     *   初回登録日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.created_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     * Database Column Remarks:
     *   最終更新ユーザーID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.updated_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer updatedBy;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.updated_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.role_code
     *
     * @return the value of user_roles.role_code
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.role_code
     *
     * @param roleCode the value for user_roles.role_code
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setRoleCode(Integer roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.role_name
     *
     * @return the value of user_roles.role_name
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.role_name
     *
     * @param roleName the value for user_roles.role_name
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.created_by
     *
     * @return the value of user_roles.created_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.created_by
     *
     * @param createdBy the value for user_roles.created_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.created_at
     *
     * @return the value of user_roles.created_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.created_at
     *
     * @param createdAt the value for user_roles.created_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.updated_by
     *
     * @return the value of user_roles.updated_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.updated_by
     *
     * @param updatedBy the value for user_roles.updated_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.updated_at
     *
     * @return the value of user_roles.updated_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.updated_at
     *
     * @param updatedAt the value for user_roles.updated_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}