package airlineReservation.infra.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   유저
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table users
 */
public class User {
    /**
     * Database Column Remarks:
     *   유저 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   권한 코드
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.role_code
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer roleCode;

    /**
     * Database Column Remarks:
     *   회원 이름
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_name
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   생년월일
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.birth_date
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private LocalDate birthDate;

    /**
     * Database Column Remarks:
     *   이메일 주소
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private String email;

    /**
     * Database Column Remarks:
     *   휴대폰 번호
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.phone_number
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private String phoneNumber;

    /**
     * Database Column Remarks:
     *   비밀번호
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private String password;

    /**
     * Database Column Remarks:
     *   탈퇴 여부
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.is_deleted
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Boolean isDeleted;

    /**
     * Database Column Remarks:
     *   최초 등록 유저 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.created_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer createdBy;

    /**
     * Database Column Remarks:
     *   최초 등록 일시
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.created_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     * Database Column Remarks:
     *   최종 수정 유저 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.updated_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private Integer updatedBy;

    /**
     * Database Column Remarks:
     *   최종 수정 일시
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.updated_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.role_code
     *
     * @return the value of users.role_code
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.role_code
     *
     * @param roleCode the value for users.role_code
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setRoleCode(Integer roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_name
     *
     * @return the value of users.user_name
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_name
     *
     * @param userName the value for users.user_name
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.birth_date
     *
     * @return the value of users.birth_date
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public LocalDate getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.birth_date
     *
     * @param birthDate the value for users.birth_date
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setBirthDate(LocalDate birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.phone_number
     *
     * @return the value of users.phone_number
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.phone_number
     *
     * @param phoneNumber the value for users.phone_number
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.is_deleted
     *
     * @return the value of users.is_deleted
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.is_deleted
     *
     * @param isDeleted the value for users.is_deleted
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.created_by
     *
     * @return the value of users.created_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.created_by
     *
     * @param createdBy the value for users.created_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.created_at
     *
     * @return the value of users.created_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.created_at
     *
     * @param createdAt the value for users.created_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.updated_by
     *
     * @return the value of users.updated_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.updated_by
     *
     * @param updatedBy the value for users.updated_by
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.updated_at
     *
     * @return the value of users.updated_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.updated_at
     *
     * @param updatedAt the value for users.updated_at
     *
     * @mbg.generated Sat Jul 25 18:49:07 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}